# Created using wingetcreate 1.9.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: WiXToolset.v3
PackageVersion: 3.14.1.8722
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
